# glpi/overlays/homelab/patch-resources.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glpi
spec:
  replicas: 1
  template:
    spec:
      initContainers:
        - name: wait-for-mysql
          image: mysql:8.0
          envFrom:
            - secretRef:
                name: glpi-mysql-secret
          command: ["sh", "-c"]
          args:
            - |
              echo "Waiting for MySQL at ${GLPI_DB_HOST:-glpi-mysql}:${GLPI_DB_PORT:-3306}..."
              until mysqladmin ping \
                -h"${GLPI_DB_HOST:-glpi-mysql}" \
                -P"${GLPI_DB_PORT:-3306}" \
                -u"${GLPI_DB_USER:-glpi}" \
                -p"${GLPI_DB_PASSWORD}" \
                --silent; do
                echo "MySQL not ready yet, sleeping..."
                sleep 3
              done
              echo "MySQL is up, starting GLPI."
      containers:
        - name: glpi
          env:
            - name: GLPI_SKIP_AUTOINSTALL
              value: "true"
            - name: GLPI_SKIP_AUTOUPDATE
              value: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glpi-mysql
spec:
  replicas: 1
