apiVersion: v1
kind: Service
metadata:
  name: glpi-mysql
  labels:
    app: glpi-mysql
spec:
  type: ClusterIP
  selector:
    app: glpi-mysql
  ports:
    - port: 3306
      targetPort: mysql
      protocol: TCP
