apiVersion: v1
kind: Secret
metadata:
  name: glpi-mysql-secret
type: Opaque
stringData:
  # MySQL
  MYSQL_ROOT_PASSWORD: "change-me-root"
  MYSQL_DATABASE: "glpi"
  MYSQL_USER: "glpi"
  MYSQL_PASSWORD: "change-me-glpi"

  # GLPI databaskoppling
  GLPI_DB_HOST: "glpi-mysql"
  GLPI_DB_PORT: "3306"
  GLPI_DB_NAME: "glpi"
  GLPI_DB_USER: "glpi"
  GLPI_DB_PASSWORD: "change-me-glpi"
