apiVersion: apps/v1
kind: Deployment
metadata:
  name: trmm-backend
  labels: { app: trmm-backend }
spec:
  replicas: 1
  selector:
    matchLabels: { app: trmm-backend }
  template:
    metadata:
      labels: { app: trmm-backend }
    spec:
      containers:
      - name: backend
        image: docker.io/tacticalrmm/tactical:1.2.0
        args: ["tactical-backend"]
        envFrom:
        - configMapRef: { name: trmm-config }
        - secretRef: { name: trmm-secrets }
        ports:
        - name: http
          containerPort: 8000
        volumeMounts:
        - { name: trmm-data, mountPath: /opt/tactical }
      volumes:
      - name: trmm-data
        persistentVolumeClaim: { claimName: trmm-data-pvc
        }
