apiVersion: apps/v1
kind: Deployment
metadata:
  name: meshcentral
  labels: { app: meshcentral }
spec:
  replicas: 1
  selector:
    matchLabels: { app: meshcentral }
  template:
    metadata:
      labels: { app: meshcentral }
    spec:
      initContainers:
      - name: mesh-init
        image: busybox:1.36
        command: ["sh","-lc"]
        args:
        - >
          set -eux;
          mkdir -p /home/node/app/meshcentral-data;
          cp -f /config/config.json /home/node/app/meshcentral-data/config.json;
          chown -R 1000:1000 /home/node/app/meshcentral-data
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        - name: mesh-data
          mountPath: /home/node/app/meshcentral-data
        - name: mesh-config
          mountPath: /config
      containers:
      - name: meshcentral
        image: docker.io/tacticalrmm/tactical-meshcentral:1.2.0
        ports:
        - name: https
          containerPort: 4443
        - name: http
          containerPort: 80
        volumeMounts:
        - name: mesh-data
          mountPath: /home/node/app/meshcentral-data
        - name: mesh-config
          mountPath: /config
      volumes:
      - name: mesh-data
        persistentVolumeClaim:
          claimName: mesh-data-pvc
      - name: mesh-config
        configMap:
          name: meshcentral-config
