apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tactical-rmm
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-dns"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
    - hosts: ["rmm.support4u.se"]
      secretName: rmm-tls
    - hosts: ["api.rmm.support4u.se"]
      secretName: rmm-api-tls
    - hosts: ["mesh.support4u.se"]
      secretName: mesh-tls
  rules:
    - host: rmm.support4u.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rmm-web
                port:
                  number: 8080
    - host: api.rmm.support4u.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rmm-api
                port:
                  number: 8000
    - host: mesh.support4u.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: meshcentral
                port:
                  number: 443
