apiVersion: batch/v1
kind: Job
metadata:
  name: trmm-init
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: init
        image: docker.io/tacticalrmm/tactical:v1.2.0
        args: ["tactical-init"]
        envFrom:
        - configMapRef: { name: trmm-config }
        - secretRef:    { name: trmm-secrets }
        volumeMounts:
        - name: trmm-data
          mountPath: /opt/tactical
      volumes:
      - name: trmm-data
        persistentVolumeClaim: { claimName: trmm-data-pvc }
