apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap-trmm-config.yaml
  - secret-trmm-secrets.yaml
  - pvc-trmm.yaml
  - deploy-backend.yaml
  - deploy-celery.yaml
  - deploy-celerybeat.yaml
  - deploy-websockets.yaml
  - svc-backend.yaml
  - svc-celery.yaml
  - svc-celerybeat.yaml
  - svc-websockets.yaml
  - deploy-redis.yaml
  - svc-redis.yaml
  - statefulset-postgres.yaml
  - svc-postgres.yaml
  - deploy-mongo.yaml
  - svc-mongo.yaml
  - deploy-meshcentral.yaml
  - svc-meshcentral.yaml
  - job-trmm-init.yaml
  - ingress-api.yaml
  - ingress-mesh.yaml
  - mesh-configmap.yaml
  - deploy-frontend.yaml
  - svc-frontend.yaml
  - ingress-frontend.yaml
