apiVersion: v1
kind: ConfigMap
metadata:
  name: meshcentral-config
data:
  config.json: |
    {
      "settings": {
        "port": 4443,
        "redirectionPort": 80,
        "cert": "mesh.support4u.se",
        "mongodb": "mongodb://mongo:27017/meshcentral",
        "wanonly": true,
        "ignoreagenthashcheck": true
      },
      "domains": {
        "": {
          "title": "MeshCentral",
          "certurl": "https://mesh.support4u.se/",
          "buildagent": true
        }
      }
    }
