apiVersion: v1
kind: Service
metadata:
  name: meshcentral
spec:
  selector:
    app: meshcentral
  ports:
    - name: https
      port: 443
      targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meshcentral
spec:
  replicas: 1
  selector:
    matchLabels: { app: meshcentral }
  template:
    metadata:
      labels: { app: meshcentral }
    spec:
      imagePullSecrets:
        - name: ghcr-cred
      containers:
        - name: meshcentral
          image: ghcr.io/ylianst/meshcentral:latest
          ports:
            - containerPort: 443
          env:
            - name: HOSTNAME
              valueFrom: { configMapKeyRef: { name: tactical-rmm-config, key: MESH_HOST } }
          volumeMounts:
            - name: mesh-data
              mountPath: /opt/meshcentral/meshcentral-data
          livenessProbe:
            tcpSocket: { port: 443 }
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            tcpSocket: { port: 443 }
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      volumes:
        - name: mesh-data
          persistentVolumeClaim:
            claimName: meshcentral-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meshcentral-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
