apiVersion: v1
kind: Service
metadata:
  name: trmm-nginx-svc
spec:
  type: LoadBalancer
  selector: { app: trmm-nginx }
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 4443
