apiVersion: v1
kind: Service
metadata:
  name: tactical-rmm-external
  labels:
    app: tactical-rmm
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
