apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels: { app: postgres }
spec:
  selector:
    matchLabels: { app: postgres }
  serviceName: "postgres"
  replicas: 1
  template:
    metadata:
      labels: { app: postgres }
    spec:
      containers:
      - name: postgres
        image: docker.io/library/postgres:15-alpine
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef: { name: trmm-secrets, key: POSTGRES_USER }
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef: { name: trmm-secrets, key: POSTGRES_PASS }
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef: { name: trmm-secrets, key: POSTGRES_DB }
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: postgres-data-pvc
