apiVersion: v1
kind: Service
metadata:
  name: meshcentral
spec:
  selector: { app: meshcentral }
  ports:
  - name: https
    port: 4443
    targetPort: 4443
  - name: http
    port: 80
    targetPort: 80
