apiVersion: apps/v1
kind: Deployment
metadata:
  name: trmm-websockets
spec:
  replicas: 1
  selector:
    matchLabels: { app: trmm-websockets }
  template:
    metadata:
      labels: { app: trmm-websockets }
    spec:
      containers:
      - name: websockets
        image: "$(IMAGE_REPO)tactical:$(VERSION)"
        command: ["tactical-websockets"]
        envFrom:
        - configMapRef: { name: trmm-config }
        - secretRef: { name: trmm-secrets }
        volumeMounts:
        - { name: trmm-data, mountPath: /opt/tactical }
      volumes:
      - name: trmm-data
        persistentVolumeClaim: { claimName: trmm-data-pvc }
