apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
spec:
  template:
    spec:
      containers:
        - name: n8n
          env:
            - name: N8N_HOST
              value: "n8n.support4u.se"
            - name: WEBHOOK_URL
              value: "https://n8n.support4u.se/"
