apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault
  namespace: external-secrets
spec:
  provider:
    vault:
      server: https://openbao.support4u.se/
      path: homelab         # KV v2 mount name in your Vault
      version: v2
      # Optional TLS config if you use custom CA:
      # caBundle: <base64-encoded-CA-cert>
      auth:
        kubernetes:
          mountPath: kubernetes
          role: eso-external-secrets
          serviceAccountRef:
            name: eso-vault
