apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: mosquitto
    path: patch-pvc.yaml
