apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-postgres
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: keycloak-postgres
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: homelab/keycloak/postgres
        property: POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-admin
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: keycloak-admin
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        KEYCLOAK_ADMIN: admin
  data:
    - secretKey: KEYCLOAK_ADMIN_PASSWORD
      remoteRef:
        key: homelab/keycloak/admin
        property: KEYCLOAK_ADMIN_PASSWORD
