creation_rules:
  - path_regex: (secret|values).*\.ya?ml$
    encrypted_regex: '^(data|stringData|.+password|.+secret|.+token)'
    age: ['age1exampleexampleexampleexampleexampleexampleexampleexample']
