
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-automation

resources:
  - deployment.yaml
  - service.yaml
  - pvc-config.yaml
  - pvc-media.yaml
labels:
  - pairs:
      app: homeassistant
      io.kompose.service: homeassistant
    includeSelectors: true
