
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-media-ceph
  labels:
    app: homeassistant
spec:
  accessModes: [ ReadWriteOnce ]
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 1Gi
