# services.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
  namespace: home-automation
spec:
  type: ClusterIP
  selector:
    app: mosquitto              # <-- matcha labels från din broker-pod
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: home-automation
spec:
  type: ClusterIP
  selector:
    app: influxdb               # <-- matcha labels från din influx-pod
  ports:
    - name: http
      port: 8086
      targetPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  labels:
    app: homeassistant
    io.kompose.service: homeassistant
spec:
  type: LoadBalancer
  # Justera om din MetalLB-IP är annorlunda
  loadBalancerIP: 10.10.10.218
  externalTrafficPolicy: Cluster
  selector:
    app: homeassistant
  ports:
    - { name: http,      port: 8123,  targetPort: 8123,  protocol: TCP }
    - { name: coiot,     port: 5683,  targetPort: 5683,  protocol: UDP }
    - { name: tcp-21063, port: 21063, targetPort: 21063, protocol: TCP }
    - { name: tcp-1400,  port: 1400,  targetPort: 1400,  protocol: TCP }
