
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: home-automation
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/MatsBerggren/gitops
        revision: main
        directories:
          - path: apps/home-automation/*            # scan app directories
  template:
    metadata:
      name: '{{path.basename}}'                     # app name = directory name
    spec:
      project: home-automation
      source:
        repoURL: https://github.com/MatsBerggren/gitops
        targetRevision: main
        path: '{{path}}/overlays/homelab'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
