apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tactical-rmm-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: tactical-rmm-secret
    creationPolicy: Owner
  data:
    - secretKey: DJANGO_SECRET_KEY
      remoteRef:
        key: kv/tactical-rmm/dev/app
        property: DJANGO_SECRET_KEY
    - secretKey: DB_NAME
      remoteRef:
        key: kv/tactical-rmm/dev/db
        property: DB_NAME
    - secretKey: DB_USER
      remoteRef:
        key: kv/tactical-rmm/dev/db
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: kv/tactical-rmm/dev/db
        property: DB_PASSWORD
    - secretKey: DB_HOST
      remoteRef:
        key: kv/tactical-rmm/dev/db
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: kv/tactical-rmm/dev/db
        property: DB_PORT
    - secretKey: REDIS_HOST
      remoteRef:
        key: kv/tactical-rmm/dev/redis
        property: REDIS_HOST
    - secretKey: REDIS_PORT
      remoteRef:
        key: kv/tactical-rmm/dev/redis
        property: REDIS_PORT
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: kv/tactical-rmm/dev/cloudflare
        property: CLOUDFLARE_API_TOKEN
