apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: trmm-secrets-sync
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: trmm-vault-store
  target:
    name: trmm-secrets
    creationPolicy: Merge
  data:
  - secretKey: TRMM_USER
    remoteRef: { key: trmm/secrets, property: TRMM_USER }
  - secretKey: TRMM_PASS
    remoteRef: { key: trmm/secrets, property: TRMM_PASS }
  - secretKey: POSTGRES_USER
    remoteRef: { key: trmm/secrets, property: POSTGRES_USER }
  - secretKey: POSTGRES_PASS
    remoteRef: { key: trmm/secrets, property: POSTGRES_PASS }
  - secretKey: MONGODB_USER
    remoteRef: { key: trmm/secrets, property: MONGODB_USER }
  - secretKey: MONGODB_PASSWORD
    remoteRef: { key: trmm/secrets, property: MONGODB_PASSWORD }
  - secretKey: MESH_USER
    remoteRef: { key: trmm/secrets, property: MESH_USER }
  - secretKey: MESH_PASS
    remoteRef: { key: trmm/secrets, property: MESH_PASS }
  - secretKey: CERT_PUB_KEY
    remoteRef: { key: trmm/secrets, property: CERT_PUB_KEY }
  - secretKey: CERT_PRIV_KEY
    remoteRef: { key: trmm/secrets, property: CERT_PRIV_KEY }
