apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tactical-rmm
resources:
  - ../../base
  - secretstore.yaml
  - externalsecret.yaml
patches:
  - path: patch-hosts.yaml
  - path: patch-storageclass.yaml
