apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-vault-auth
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: https://openbao.support4u.se
      path: homelab
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: tactical-rmm
          serviceAccountRef:
            name: eso-vault-auth
