apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blackbox-exporter
  namespace: monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: blackbox-exporter
  endpoints:
    - port: http
      interval: 30s
