apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
  - ../../base
patches:
  - target:
      kind: SecretStore
      name: vault
    patch: |-
      - op: replace
        path: /kind
        value: ClusterSecretStore
      - op: remove
        path: /metadata/namespace
