apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  labels:
    app.kubernetes.io/instance: root-homelab
spec:
  project: monitoring
  source:
    repoURL: https://github.com/MatsBerggren/gitops
    targetRevision: main
    path: apps/monitoring/monitoring/overlays/homelab
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
