apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-helm
  namespace: argocd
spec:
  project: observability
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 70.4.0
    helm:
      releaseName: kube-prometheus-stack
      values: |
        fullnameOverride: kube-prometheus-stack

        grafana:
          enabled: true
          adminPassword: "YY8I36ETJKxvaYH15ARigUaLrmz5Pjzm"
          service:
            type: ClusterIP

        prometheus-node-exporter:
          enabled: false

        prometheus:
          prometheusSpec:
            retention: 15d

        alertmanager:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
