apiVersion: v1
kind: Secret
metadata:
  name: pve-exporter
  namespace: monitor
type: Opaque
stringData:
  PVE_USER: "root@pam"
  PVE_TOKEN_NAME: "Monitoring"
  PVE_TOKEN_VALUE: "6f38a828-bc47-45b6-b2d2-360f8b737feb"
