apiVersion: monitor.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pve-exporter
  namespace: monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: pve-exporter
  endpoints:
    - port: http
      interval: 60s
      path: /pve
      params:
        target:
          - 10.10.10.11
          - 10.10.10.12
          - 10.10.10.13
