apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore  # switch to SecretStore if you didn't apply cluster overlay
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: api-token
      remoteRef:
        key: infra/cloudflare
        property: API_TOKEN
