apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmm-api
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmm-daphne
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmm-nginx
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmm-celery
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmm-celerybeat
spec:
  replicas: 1
