apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwisp-nginx
  namespace: openwisp
spec:
  template:
    spec:
      volumes:
      - name: nginx-config
        configMap:
          name: openwisp-nginx-config
      containers:
      - name: openwisp-nginx
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
