apiVersion: v1
kind: ConfigMap
metadata:
  name: openbao-config
  namespace: openbao
data:
  config.tmpl: |
    # Listener for API + cluster traffic
    listener "tcp" {
      address          = "0.0.0.0:8200"
      cluster_address  = "0.0.0.0:8201"
      tls_disable      = "true"
    }

    # Explicit addresses required for raft
    api_addr     = "http://__POD_NAME__.openbao.openbao.svc:8200"
    cluster_addr = "http://__POD_IP__:8201"

    storage "raft" {
      path    = "/data"
      node_id = "__POD_NAME__"
      retry_join {
        leader_api_addr = "http://openbao-0.openbao.openbao.svc:8200"
      }
    }

    ui = true
