apiVersion: v1
kind: ConfigMap
metadata:
  name: openbao-config
  namespace: openbao
data:
  config.hcl: |
    ui = true

    storage "file" {
      path = "/bao/data"
    }

    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = 1
    }

    disable_mlock = true
