apiVersion: v1
kind: ConfigMap
metadata:
  name: openbao-config
  namespace: openbao
data:
  config.hcl: |
    # Listener for API + cluster traffic
    listener "tcp" {
      address          = "0.0.0.0:8200"
      cluster_address  = "0.0.0.0:8201"
      tls_disable      = "true"
    }

    # For raft clusters we only need a stable leader address for first join.
    # Avoid env interpolation by using full pod DNS in the known namespace.
    storage "raft" {
      path    = "/data"
      node_id = "{{env \"HOSTNAME\"}}"
      retry_join {
        leader_api_addr = "http://openbao-0.openbao.openbao.svc:8200"
      }
    }

    ui = true
