apiVersion: v1
kind: ConfigMap
metadata:
  name: openbao-config
  namespace: openbao
data:
  config.hcl: |
    listener "tcp" {
      address       = "0.0.0.0:8200"
      tls_disable   = "true"
    }

    storage "raft" {
      path    = "/data"
      node_id = "$(HOSTNAME)"
    }

    ui = true
