apiVersion: v1
kind: ConfigMap
metadata:
  name: openbao-config
  namespace: openbao
data:
  config.hcl: |
    # Listener for API + cluster traffic
    listener "tcp" {
      address          = "0.0.0.0:8200"
      cluster_address  = "0.0.0.0:8201"
      tls_disable      = "true"
    }

    # Single-node integrated storage (Raft) -- no retry_join
    api_addr     = "http://openbao.openbao.svc:8200"
    cluster_addr = "http://127.0.0.1:8201"

    storage "raft" {
      path    = "/data"
      node_id = "openbao-0"
    }

    ui = true
