apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openbao
  namespace: openbao
  annotations:
    # argocd.argoproj.io/sync-options: Replace=true
spec:
  serviceName: openbao
  replicas: 1
  selector:
    matchLabels:
      app: openbao
  template:
    metadata:
      labels:
        app: openbao
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      initContainers:
        - name: volume-permissions
          image: busybox:1.36
          command: ['sh','-c','chown -R 1000:1000 /data && chmod -R u+rwX,g-rwx,o-rwx /data']
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: data
              mountPath: /data
      containers:
        - name: openbao
          image: ghcr.io/openbao/openbao:latest
          args: ["server", "-config=/etc/openbao/config.hcl"]
          ports:
            - containerPort: 8200
              name: api
            - containerPort: 8201
              name: cluster
          readinessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204
              port: 8200
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204
              port: 8200
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 12
          volumeMounts:
            - name: config
              mountPath: /etc/openbao
              readOnly: true
            - name: data
              mountPath: /data
      volumes:
        - name: config
          configMap:
            name: openbao-config
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
        storageClassName: ceph-rbd
