
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-conf
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/
    listener 1883
    allow_anonymous true
    # För produktion: sätt password_file, require_certificate, etc.
