
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: mqtt
              containerPort: 1883
              protocol: TCP
          volumeMounts:
            - name: mosquitto-conf
              mountPath: /mosquitto/config
            - name: mosquitto-data
              mountPath: /mosquitto/data
      volumes:
        - name: mosquitto-conf
          configMap:
            name: mosquitto-conf
            items:
              - key: mosquitto.conf
                path: mosquitto.conf
        - name: mosquitto-data
          persistentVolumeClaim:
            claimName: mosquitto-data
