
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-automation

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
labels:
  - pairs:
      app: mosquitto
    includeSelectors: true
