
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
  labels:
    app: mosquitto
spec:
  accessModes: [ ReadWriteOnce ]
  storageClassName: local-path
  resources:
    requests:
      storage: 512Mi
