apiVersion: v1
kind: ConfigMap
metadata:
  name: avahi-config
  namespace: network
data:
  avahi-daemon.conf: |
    [server]
    domain-name=local
    use-ipv4=yes
    use-ipv6=no
    allow-interfaces=bond0.10,bond0.50,bond0.60
    deny-interfaces=docker0,virbr*,veth*,cni*,flannel*,kube-ipvs*,lo

    [reflector]
    enable-reflector=yes
    reflect-ipv=no

    [wide-area]
    enable-wide-area=no

    [publish]
    disable-publishing=yes
    disable-user-service-publishing=yes
    add-service-cookie=no
