apiVersion: v1
kind: Service
metadata:
  name: openwisp-api
  namespace: openwisp
spec:
  type: ClusterIP
  selector:
    app: openwisp-api
  ports:
    - port: 8000
      targetPort: 8000
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwisp-api
  namespace: openwisp
  labels:
    app: openwisp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openwisp-api
  template:
    metadata:
      labels:
        app: openwisp-api
    spec:
      containers:
        - name: api
          image: openwisp/openwisp-controller:latest
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - configMapRef:
                name: openwisp-config
            - secretRef:
                name: openwisp-secret
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
