apiVersion: v1
kind: Service
metadata:
  name: openwisp-influxdb
  labels:
    app: openwisp-influxdb
spec:
  selector:
    app: openwisp-influxdb
  ports:
    - name: http
      port: 8086
      targetPort: 8086
