apiVersion: v1
kind: Service
metadata:
  name: openwisp-openvpn
  namespace: openwisp
  annotations:
    metallb.universe.tf/address-pool: lb-pool    # ändra om du har annan pool
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - name: openvpn
      port: 1194
      targetPort: 1194
      protocol: UDP
  selector: {}   # inga pods -> vi kopplar endpoints manuellt
