apiVersion: v1
kind: Service
metadata:
  name: openwisp-redis
  namespace: openwisp
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app: openwisp-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwisp-redis
  namespace: openwisp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openwisp-redis
  template:
    metadata:
      labels:
        app: openwisp-redis
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
              name: redis
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
