apiVersion: v1
kind: Service
metadata:
  name: openwisp-websocket
  namespace: openwisp
spec:
  type: ClusterIP
  selector:
    app: openwisp-websocket
  ports:
    - port: 8000
      targetPort: 8000
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwisp-websocket
  namespace: openwisp
  labels:
    app: openwisp-websocket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openwisp-websocket
  template:
    metadata:
      labels:
        app: openwisp-websocket
    spec:
      containers:
        - name: websocket
          image: openwisp/openwisp-websocket:latest
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - configMapRef:
                name: openwisp-config
            - secretRef:
                name: openwisp-secret
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
