apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodered-data
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 5Gi
