apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data-nfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Ti
  volumeName: minio-data-nfs-pv
  storageClassName: nfs-md1200
  volumeMode: Filesystem
