apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data-nfs
spec:
  capacity:
    storage: 2Ti
  nfs:
    server: 10.10.82.13
    path: /md1200/minio
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-md1200
