apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wordpress

resources:
  - namespace.yaml
  - redis-secret.yaml
  - redis-statefulset.yaml
  - redis-service.yaml

patches:
  - path: wordpress-patch.yaml
    target:
      kind: Deployment
      name: wordpress
      namespace: wordpress
