apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wordpress

resources:
  - redis-secret.yaml
  - redis-statefulset.yaml
  - redis-service.yaml

patches:
  - path: wordpress-env-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      labelSelector: "app=wordpress"
