apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: wordpress
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: redis
          image: redis:7.2-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              name: redis
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-auth
                  key: redis-password
          command:
            - sh
            - -c
            - >
              exec redis-server
              --appendonly yes
              --requirepass "$REDIS_PASSWORD"
              --bind 0.0.0.0
              --protected-mode no
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: data
              mountPath: /data
          livenessProbe:
            tcpSocket: { port: 6379 }
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - sh
                - -lc
                - redis-cli -a "$REDIS_PASSWORD" ping | grep -q PONG
            initialDelaySeconds: 5
            periodSeconds: 10
          startupProbe:
            tcpSocket: { port: 6379 }
            periodSeconds: 5
            failureThreshold: 12
  volumeClaimTemplates:
    # (A) Vill du att Argo slutar “diffa”: behåll apiVersion/kind här.
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ceph-rbd
        resources:
          requests:
            storage: 2Gi
    # (B) Alternativ: ta bort apiVersion/kind om du hellre använder Argo ignoreDifferences.
