apiVersion: apps/v1
kind: Deployment
metadata:
  # name medvetet utelämnat – vi matchar på label istället
spec:
  template:
    spec:
      containers:
        - name: wordpress        # behåll om din container heter "wordpress"
          env:
            - name: REDIS_HOST
              value: "redis.wordpress.svc.cluster.local"     # eller "redis.wordpress.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-auth
                  key: redis-password
            - name: WP_CACHE_KEY_SALT
              value: "wp:www.taberg.info:"   # BYT till något unikt
            - name: WORDPRESS_CONFIG_EXTRA
              value: |
                if (!defined('WP_REDIS_HOST'))  define('WP_REDIS_HOST', getenv('REDIS_HOST'));
                if (!defined('WP_REDIS_PORT'))  define('WP_REDIS_PORT', intval(getenv('REDIS_PORT') ?: '6379'));
                if (!defined('WP_REDIS_PASSWORD')) define('WP_REDIS_PASSWORD', getenv('REDIS_PASSWORD') ?: null);
                if (!defined('WP_CACHE_KEY_SALT')) define('WP_CACHE_KEY_SALT', getenv('WP_CACHE_KEY_SALT') ?: 'wp:site:');
                if (!defined('WP_REDIS_DATABASE')) define('WP_REDIS_DATABASE', 0);
                if (!defined('WP_CACHE')) define('WP_CACHE', true);
