apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero-cloud-credentials
  namespace: velero
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: cloud-credentials
    creationPolicy: Owner
  data:
    - secretKey: cloud
      remoteRef:
        key: velero/cloud
        property: cloud
