apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velero
resources:
  - namespace.yaml
  - externalsecret-credentials.yaml
  - velero-ui-rbac.yaml
  - velero-ui-ingress.yaml
  - resources
