apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velero
resources:
  - ../../base
  - externalsecret-credentials.yaml

# Ensure we don't also keep the placeholder Secret from base once ExternalSecrets is in use.
patches:
  - target:
      kind: Secret
      name: cloud-credentials
    patch: |-
      - op: replace
        path: /metadata/name
        value: cloud-credentials-placeholder
