apiVersion: v1
kind: Service
metadata:
  name: proxmox-external
  namespace: default
spec:
  type: ExternalName
  externalName: 10.10.10.11
  ports:
    - port: 8006
      targetPort: 8006
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxmox
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-verify: "off"
spec:
  ingressClassName: nginx
  rules:
    - host: proxmox.support4u.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxmox-external
                port:
                  number: 8006
  tls:
    - hosts:
        - proxmox.support4u.se
      secretName: tls-proxmox
