apiVersion: v1
kind: ConfigMap
metadata:
  name: z2m-config
data:
  configuration.yaml: |
    homeassistant: true
    permit_join: false
    mqtt:
      base_topic: zigbee2mqtt
      server: mqtt://mosquitto.home-automation.svc.cluster.local:1883
      user: "ha"
      password: "CHANGEME"
    serial:
      port: tcp://slzb-06m.home.arpa:6638
      adapter: ezsp
    frontend: true
