apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels: { app: zigbee2mqtt }
  template:
    metadata:
      labels: { app: zigbee2mqtt }
    spec:
      containers:
        - name: zigbee2mqtt
          image: koenkk/zigbee2mqtt:latest
          env:
            - name: TZ
              value: "Europe/Stockholm"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /app/data
            - name: z2m-config
              mountPath: /app/data/configuration.yaml
              subPath: configuration.yaml
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: zigbee2mqtt
        - name: z2m-config
          configMap:
            name: z2m-config
