
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  labels:
    app: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      containers:
        - name: zigbee2mqtt
          image: ghcr.io/koenkk/zigbee2mqtt:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            - name: TZ
              value: Europe/Stockholm
            - name: ZIGBEE2MQTT_CONFIG_SERIAL_PORT
              value: tcp://10.10.60.100:6638
            - name: ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER
              value: ember
            - name: ZIGBEE2MQTT_CONFIG_MQTT_SERVER
              value: mqtt://mosquitto:1883
            - name: ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC
              value: zigbee2mqtt
            - name: ZIGBEE2MQTT_CONFIG_FRONTEND_ENABLED
              value: "true"
          ports:
            - name: ui
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: zigbee2mqtt-data
              mountPath: /app/data
      volumes:
        - name: zigbee2mqtt-data
          persistentVolumeClaim:
            claimName: zigbee2mqtt-data
