
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-data
  labels:
    app: zigbee2mqtt
spec:
  accessModes: [ ReadWriteOnce ]
  storageClassName: local-path
  resources:
    requests:
      storage: 512Mi
