apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

secretGenerator:
  - name: grafana-admin
    literals:
      - username=admin
      - password=YY8I36ETJKxvaYH15ARigUaLrmz5Pjzm
