apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
spec:
  tls:
    - hosts: ["homeassistant.support4u.se"]
      secretName: home-assistant-tls
  rules:
    - host: homeassistant.support4u.se
