apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # Argo CD external URL (must match ingress host)
  url: https://argocd.support4u.se

  # Native OIDC (skip Dex)
  oidc.config: |
    name: Keycloak
    issuer: https://auth.support4u.se/realms/HomeLab
    clientID: argocd
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes:
      - openid
      - profile
      - email

  # Allow Kustomize to render helmCharts/HelmChartInflationGenerator
  kustomize.buildOptions: "--enable-helm"
