apiVersion: monitor.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: snmp-exporter
  namespace: monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: snmp-exporter
  endpoints:
    - port: http
      interval: 30s
