apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
  labels:
    app.kubernetes.io/instance: root-homelab
spec:
  description: Monitoring stack (Prometheus/Grafana/Alertmanager + exporters)
  destinations:
    - namespace: monitoring
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/MatsBerggren/gitops
    - https://prometheus-community.github.io/helm-charts
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
