
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: home-automation
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/MatsBerggren/gitops
        revision: main
        directories:
          - path: apps/home-automation/*/overlays/homelab
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/MatsBerggren/gitops
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: home-automation
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
