apiVersion: batch/v1
kind: CronJob
metadata:
  name: wp-cron
  namespace: wordpress
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:8.10.1
            args: ["-sS","https://www.taberg.info/wp-cron.php?doing_wp_cron=1"]
          restartPolicy: OnFailure
