apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-tuning
  namespace: wordpress
data:
  zz-tuning.cnf: |
    [mysqld]
    # ~60–70% of container memory limit (we will set 2Gi limit -> ~1.3Gi)
    innodb_buffer_pool_size=1300M
    innodb_buffer_pool_instances=1
    innodb_log_file_size=256M

    # Disable query cache (recommended)
    query_cache_type=0
    query_cache_size=0

    # Pragmatic defaults for WP-sized workloads
    max_connections=200
    table_open_cache=2048
    tmp_table_size=64M
    max_heap_table_size=64M
