apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
spec:
  template:
    spec:
      containers:
      - name: wordpress
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits: {}   # no CPU/MEM limits to avoid throttling
