apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      # Hjälper NFS-volymer med rätt rättigheter (Influx kör som uid 1000)
      securityContext:
        fsGroup: 1000
      containers:
        - name: influxdb
          image: influxdb:2.7
          ports:
            - name: http
              containerPort: 8086
          envFrom:
            - secretRef:
                name: influx-init
          volumeMounts:
            - name: data
              mountPath: /var/lib/influxdb2
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: influxdb-data
