apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: influx

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

# Skapar hemligheter för "influx setup" via containerns entrypoint
secretGenerator:
  - name: influx-init
    literals:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=Agnes2001!  # byt
      - DOCKER_INFLUXDB_INIT_ORG=homelab
      - DOCKER_INFLUXDB_INIT_BUCKET=default
      - DOCKER_INFLUXDB_INIT_RETENTION=0
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=byt-mig-super-token
