
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-claim1
  labels:
    app: homeassistant
spec:
  accessModes: [ ReadWriteOnce ]
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
