apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wiki-postgres-secret
  namespace: wiki-js
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: wiki-postgres-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        POSTGRES_DB: wiki
        POSTGRES_USER: wikijs
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: homelab/wiki-js/postgres
        property: POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wiki-secret
  namespace: wiki-js
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: wiki-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_TYPE: postgres
        DB_HOST: wiki-postgres
        DB_PORT: "5432"
        DB_NAME: wiki
        DB_USER: wikijs
  data:
    - secretKey: DB_PASS
      remoteRef:
        key: homelab/wiki-js/postgres
        property: POSTGRES_PASSWORD
