apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolbox
  labels:
    app: toolbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toolbox
  template:
    metadata:
      labels:
        app: toolbox
    spec:
      containers:
        - name: toolbox
          image: ghcr.io/MatsBerggren/toolbox:latest
          imagePullPolicy: IfNotPresent
          command: ["bash","-lc","sleep infinity"]
          tty: true
          stdin: true
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
      tolerations:
        - operator: "Exists"
