apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n
commonLabels:
  app.kubernetes.io/name: n8n
  app.kubernetes.io/part-of: n8n
resources:
  - namespace.yaml
  - secret-encryption.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
