# NOTE: Replace the placeholder value before applying in production.
# Consider using SealedSecrets/External Secrets instead of a plain Secret.
apiVersion: v1
kind: Secret
metadata:
  name: n8n-encryption
  namespace: n8n
type: Opaque
stringData:
  N8N_ENCRYPTION_KEY: "CHANGE-ME-TO-A-LONG-RANDOM-SECRET"
