# gitops/clusters/homelab/apps/platform/rancher/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate.yaml
patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: rancher
      namespace: cattle-system
    path: patch-ingress.yaml
