apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-rbd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-db
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph-rbd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 60Gi
  storageClassName: ceph-rbd
