apiVersion: v1
kind: Service
metadata:
  name: frigate
spec:
  type: ClusterIP
  selector:
    app: frigate
  ports:
    - name: http
      port: 5000
      targetPort: 5000
    - name: rtsp
      port: 8554
      targetPort: 8554
    - name: webrtc
      port: 8555
      targetPort: 8555
