apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wordpress
resources:
  - ../../base
patches:
  - target:
      kind: StatefulSet
      name: mariadb
    patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: local-path
  - target:
      kind: PersistentVolumeClaim
      name: wp-content
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: local-path
      - op: replace
        path: /spec/accessModes
        value:
          - ReadWriteOnce
