apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: wordpress
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: wordpress
spec:
  serviceName: mariadb
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mariadb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mariadb
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: mariadb
          image: mariadb:11.4
          imagePullPolicy: IfNotPresent
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wp-db-secret
                  key: mariadb-root-password
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: wp-db-secret
                  key: mariadb-user
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wp-db-secret
                  key: mariadb-password
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: wp-db-secret
                  key: mariadb-database
          ports:
            - name: mysql
              containerPort: 3306
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - >-
                  mariadb-admin ping
                  -h 127.0.0.1
                  -u "$MARIADB_USER"
                  -p"$MARIADB_PASSWORD"
                  --silent
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            exec:
              command: ["sh","-c","mysqladmin ping -h 127.0.0.1 -uroot -p$MARIADB_ROOT_PASSWORD"]
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mariadb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn
        resources:
          requests:
            storage: 10Gi
