apiVersion: v1
kind: Secret
metadata:
  name: wp-db-secret
  namespace: wordpress
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/part-of: wordpress
type: Opaque
stringData:
  mariadb-root-password: "CHANGE_ME_ROOT"
  mariadb-user: "wpuser"
  mariadb-password: "CHANGE_ME_USER_PASS"
  mariadb-database: "wordpress"
