apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
stringData:
  mariadb-root-password: "change-me-root"
  mariadb-user: "wpuser"
  mariadb-password: "change-me-wp"
  mariadb-database: "wordpress"
