apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-content-rbd
  namespace: wordpress
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 10Gi
